"""encrypt totp secrets at rest

A TOTP secret cannot be hashed — verifying a code means recomputing it — so it
was stored in the clear, and one `SELECT` on this table yielded a working second
factor for every enrolled account. It is now encrypted under a key held outside
the database; see `core.security.encrypt_secret`.

**This migration does not convert existing enrolments.** It refuses to run while
any exist, rather than doing either of the things an autogenerated version would:
dropping the column would silently leave those people with a password and no
second factor, which is a security downgrade nobody would be told about, and
adding a `NOT NULL` column beside their rows would simply fail with an error
about constraints that says nothing about why.

Clearing them is therefore a deliberate act, and the people affected re-enrol:

    DELETE FROM totp_credentials;

Revision ID: 9f2512366bf8
Revises: 4fdd2f4c7690
Create Date: 2026-09-22 21:06:18.750714
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9f2512366bf8"
down_revision: str | None = "4fdd2f4c7690"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

REFUSAL = (
    "totp_credentials still holds {count} enrolment(s), and this migration "
    "cannot convert them: the new column is encrypted and the old one is not. "
    "Dropping them would leave those accounts with no second factor and no "
    "notice that it had gone. Clear them deliberately and have those people "
    "enrol again:\n\n    DELETE FROM totp_credentials;\n"
)


def _refuse_if_enrolled() -> None:
    count = op.get_bind().scalar(sa.text("SELECT count(*) FROM totp_credentials")) or 0
    if count:
        raise RuntimeError(REFUSAL.format(count=count))


def upgrade() -> None:
    _refuse_if_enrolled()
    op.add_column(
        "totp_credentials",
        sa.Column("secret_encrypted", sa.String(length=255), nullable=False),
    )
    op.drop_column("totp_credentials", "secret")


def downgrade() -> None:
    # Symmetrical, and for the same reason: the ciphertext is not a TOTP secret,
    # so a downgrade that kept the rows would leave `secret` holding values no
    # authenticator app ever produced codes from.
    _refuse_if_enrolled()
    op.add_column(
        "totp_credentials",
        sa.Column("secret", sa.VARCHAR(length=255), nullable=False),
    )
    op.drop_column("totp_credentials", "secret_encrypted")
