"""What a developer is allowed to say about their own application.

The fields absent here are the point of the module. `allowedGrants`,
`skipConsent`, `isSystem`, `clientId`, and both scope assignments are decided by
the server, not by the registrant — see `service.py` for why each one is.
"""

from datetime import datetime
from typing import Literal
from uuid import UUID

from pydantic import Field, field_validator

from provider.core.schemas import CamelCaseBaseModel
from provider.shared.client_uris import REDIRECT_URI_RULES, validate_redirect_uris

# A quota, not a rule: five callbacks is more than an application needs, and a
# showcase with fifty participants should not let one of them fill the column.
MAX_URIS = 5


class ApplicationCreate(CamelCaseBaseModel):
    name: str = Field(
        min_length=1,
        max_length=255,
        description="Shown to people on the consent screen. Name it after the app.",
    )
    client_type: Literal["public", "confidential"] = Field(
        description=(
            "`public` — a browser or mobile app that cannot keep a secret; PKCE "
            "proves it. `confidential` — a server-side app; gets a secret."
        )
    )
    redirect_uris: list[str] = Field(
        min_length=1,
        description=f"Where `/authorize` may send the browser back. {REDIRECT_URI_RULES}",
    )
    post_logout_redirect_uris: list[str] = Field(
        default_factory=list,
        description="Where `/oauth2/logout` may return to. Same rules as `redirectUris`.",
    )

    @field_validator("redirect_uris", "post_logout_redirect_uris")
    @classmethod
    def check_uris(cls, values: list[str]) -> list[str]:
        return validate_redirect_uris(values, maximum=MAX_URIS)


class ApplicationUpdate(CamelCaseBaseModel):
    """Every field is optional; the ones left out are untouched.

    `clientType` is absent on purpose — it decides whether a secret exists at
    all, and flipping it would either orphan a live secret or silently leave an
    app that believes it has one.
    """

    name: str | None = Field(default=None, min_length=1, max_length=255)
    redirect_uris: list[str] | None = Field(default=None, min_length=1)
    post_logout_redirect_uris: list[str] | None = None

    @field_validator("redirect_uris", "post_logout_redirect_uris")
    @classmethod
    def check_uris(cls, values: list[str] | None) -> list[str] | None:
        return (
            None if values is None else validate_redirect_uris(values, maximum=MAX_URIS)
        )


class ApplicationResponse(CamelCaseBaseModel):
    id: UUID
    client_id: str = Field(
        description="Generated by IDEN. This is what your app sends at `/authorize`."
    )
    name: str
    client_type: Literal["public", "confidential"]
    allowed_grants: list[str] = Field(
        description="Fixed: the authorization code flow, with refresh."
    )
    redirect_uris: list[str]
    post_logout_redirect_uris: list[str]
    grantable_scopes: list[str] = Field(
        description=(
            "Everything this application may put in its `scope` parameter. The "
            "OpenID Connect scopes are always there; anything beyond them was "
            "attached by an administrator."
        )
    )
    has_secret: bool = Field(
        description="Whether a client secret exists. Its value is never readable."
    )
    created_at: datetime


class ApplicationCreated(ApplicationResponse):
    client_secret: str | None = Field(
        default=None,
        description=(
            "Shown **once**, here. It is argon2-hashed on the way in and cannot "
            "be recovered — only rotated. Null for a public application."
        ),
    )


class ApplicationList(CamelCaseBaseModel):
    applications: list[ApplicationResponse]
    remaining: int = Field(
        description="How many more applications this account may register."
    )


class SecretRotated(CamelCaseBaseModel):
    client_secret: str = Field(
        description="Shown once. The previous secret stops working now."
    )
